/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	hadoopv1 "github.com/HenryGits/hadoop-operator/apis/hadoop/v1"
	versioned "github.com/HenryGits/hadoop-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/HenryGits/hadoop-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/HenryGits/hadoop-operator/pkg/client/listers/hadoop/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HadoopInformer provides access to a shared informer and lister for
// Hadoops.
type HadoopInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HadoopLister
}

type hadoopInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHadoopInformer constructs a new informer for Hadoop type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHadoopInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHadoopInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHadoopInformer constructs a new informer for Hadoop type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHadoopInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HadoopV1().Hadoops(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HadoopV1().Hadoops(namespace).Watch(context.TODO(), options)
			},
		},
		&hadoopv1.Hadoop{},
		resyncPeriod,
		indexers,
	)
}

func (f *hadoopInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHadoopInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hadoopInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hadoopv1.Hadoop{}, f.defaultInformer)
}

func (f *hadoopInformer) Lister() v1.HadoopLister {
	return v1.NewHadoopLister(f.Informer().GetIndexer())
}
