FROM centos:7
LABEL REPOSITORY=zhc/hadoop TAG=3.3.1

ENV JAVA_HOME=/usr/local/jdk
ENV CLASSPATH=.:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar
ENV PATH=$PATH:${JAVA_HOME}/bin

RUN echo $' \n\
[base]  \n\
name=CentOS7-Base \n\
baseurl=http://mirrors.163.com/centos/7/os/x86_64/ \n\
gpgcheck=0 \n\
gpgkey=http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-7' > /etc/yum.repos.d/CentOS-Base.repo
RUN cat /etc/yum.repos.d/CentOS-Base.repo
RUN yum clean all && yum makecache fast

# 安装jdk依赖包
RUN yum install -y --nogpgcheck net-tools


COPY  jdk /usr/local/jdk
COPY  hadoop /usr/local/hadoop
COPY  entrypoint.sh /entrypoint.sh

RUN chmod a+x /entrypoint.sh

EXPOSE 9870 9871 8088

ENTRYPOINT ["/entrypoint.sh"]
