# permissions for end users to view hadoops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hadoop-viewer-role
rules:
- apiGroups:
  - hadoop.dameng.com
  resources:
  - hadoops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hadoop.dameng.com
  resources:
  - hadoops/status
  verbs:
  - get
