# permissions for end users to edit hadoops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hadoop-editor-role
  namespace: system
rules:
- apiGroups:
  - hadoop.dameng.com
  resources:
  - hadoops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hadoop.dameng.com
  resources:
  - hadoops/status
  verbs:
  - get
