---
apiVersion: hadoop.dameng.com/v1
kind: Hadoop
metadata:
  name: hadoop-sample
  namespace: system
spec:
  id: "id"
  title: "title"
  describe: "describe"
  # The base hadoop image to use for all components.
  # See this repo for image build details: https://github.com/chenseanxy/helm-hadoop-3/tree/master/image
  container:
    image: hadoop:v3.3.1
    pullPolicy: IfNotPresent
  hdfs:
    nameNode:
      replicas: 2
      resources:
        requests:
          memory: "256Mi"
          cpu:  "100m"
        limits:
          memory: "2048Mi"
          cpu:  "1000m"
    dataNode:
      replicas: 2
      resources:
        requests:
          memory: "256Mi"
          cpu:  "100m"
        limits:
          memory: "2048Mi"
          cpu:  "1000m"
  webHdfs:
    enabled: true
  resourceManager:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"
  nodeManager:
    replicas: 2
    parallelCreate: false
    resources:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  historyServer:
    parallelCreate: false
    resources:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
