---
apiVersion: hadoop.dameng.com/v1
kind: Hadoop
metadata:
  name: hadoop-sample
  namespace: system
spec:
  id: "id"
  title: "title"
  describe: "describe"
  nameNode:
    daemonSet:
      metadata:
        name: nn
        namespace: system
      spec:
        selector:
          matchLabels:
            app: nn
        template:
          metadata:
            labels:
              app: nn
          spec:
            serviceAccountName: hadoop-nn-admin
            containers:
              - image: "hadoop:v3.3.1"
                imagePullPolicy: "IfNotPresent"
                name: provisioner
                securityContext:
                  privileged: true
                env:
                - name: MY_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                volumeMounts:
      #            - name: provisioner-config
      #              mountPath: /etc/provisioner/config
      #              readOnly: true
                  - name: nn-dir
                    mountPath: /usr/local/hadoop/nn
                    mountPropagation: "HostToContainer"
                resources:
                  requests:
                    memory: "256Mi"
                    cpu: "100m"
                  limits:
                    memory: "2048Mi"
                    cpu: "1000m"
            volumes:
      #        - name: provisioner-config
      #          configMap:
      #            name: local-provisioner-config
              - name: nn-dir
                hostPath:
                  # Ensure the file directory is created.
                  path: /home/data
                  type: DirectoryOrCreate
    dataNode:
      daemonSet:
        metadata:
          name: dn
          namespace: system
        spec:
          selector:
            matchLabels:
              app: dn
          template:
            metadata:
              labels:
                app: dn
            spec:
              serviceAccountName: hadoop-nn-admin
              containers:
                - image: "hadoop:v3.3.1"
                  imagePullPolicy: "IfNotPresent"
                  name: provisioner
                  securityContext:
                    privileged: true
                  env:
                  - name: MY_NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                  volumeMounts:
        #            - name: provisioner-config
        #              mountPath: /etc/provisioner/config
        #              readOnly: true
                    - name: nn-dir
                      mountPath: /usr/local/hadoop/dn
                      mountPropagation: "HostToContainer"
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "100m"
                    limits:
                      memory: "2048Mi"
                      cpu: "1000m"
              volumes:
        #        - name: provisioner-config
        #          configMap:
        #            name: local-provisioner-config
                - name: nn-dir
                  hostPath:
                    # Ensure the file directory is created.
                    path: /home/data
                    type: DirectoryOrCreate
    webHdfs:
      enabled: true

  yarn:
    resourceManager:
      pdbMinAvailable: 1

      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "2048Mi"
          cpu: "2000m"

    nodeManager:
      pdbMinAvailable: 1

      # The number of YARN NodeManager instances.
      replicas: 2

      # Create statefulsets in parallel (K8S 1.7+)
      parallelCreate: false

      # CPU and memory resources allocated to each node manager pod.
      # This should be tuned to fit your workload.
      resources:
        requests:
          memory: "2048Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "1000m"

  persistence:
    nameNode:
      enabled: false
      storageClass: "-"
      accessMode: ReadWriteOnce
      size: 50Gi

    dataNode:
      enabled: false
      storageClass: "-"
      accessMode: ReadWriteOnce
      size: 200Gi

  postInstallCommands: []
