/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	hadoopv1 "github.com/HenryGits/hadoop-operator/apis/hadoop/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHadoops implements HadoopInterface
type FakeHadoops struct {
	Fake *FakeHadoopV1
	ns   string
}

var hadoopsResource = schema.GroupVersionResource{Group: "hadoop.dameng.com", Version: "v1", Resource: "hadoops"}

var hadoopsKind = schema.GroupVersionKind{Group: "hadoop.dameng.com", Version: "v1", Kind: "Hadoop"}

// Get takes name of the hadoop, and returns the corresponding hadoop object, and an error if there is any.
func (c *FakeHadoops) Get(ctx context.Context, name string, options v1.GetOptions) (result *hadoopv1.Hadoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hadoopsResource, c.ns, name), &hadoopv1.Hadoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hadoopv1.Hadoop), err
}

// List takes label and field selectors, and returns the list of Hadoops that match those selectors.
func (c *FakeHadoops) List(ctx context.Context, opts v1.ListOptions) (result *hadoopv1.HadoopList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hadoopsResource, hadoopsKind, c.ns, opts), &hadoopv1.HadoopList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hadoopv1.HadoopList{ListMeta: obj.(*hadoopv1.HadoopList).ListMeta}
	for _, item := range obj.(*hadoopv1.HadoopList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hadoops.
func (c *FakeHadoops) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hadoopsResource, c.ns, opts))

}

// Create takes the representation of a hadoop and creates it.  Returns the server's representation of the hadoop, and an error, if there is any.
func (c *FakeHadoops) Create(ctx context.Context, hadoop *hadoopv1.Hadoop, opts v1.CreateOptions) (result *hadoopv1.Hadoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hadoopsResource, c.ns, hadoop), &hadoopv1.Hadoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hadoopv1.Hadoop), err
}

// Update takes the representation of a hadoop and updates it. Returns the server's representation of the hadoop, and an error, if there is any.
func (c *FakeHadoops) Update(ctx context.Context, hadoop *hadoopv1.Hadoop, opts v1.UpdateOptions) (result *hadoopv1.Hadoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hadoopsResource, c.ns, hadoop), &hadoopv1.Hadoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hadoopv1.Hadoop), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHadoops) UpdateStatus(ctx context.Context, hadoop *hadoopv1.Hadoop, opts v1.UpdateOptions) (*hadoopv1.Hadoop, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hadoopsResource, "status", c.ns, hadoop), &hadoopv1.Hadoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hadoopv1.Hadoop), err
}

// Delete takes name of the hadoop and deletes it. Returns an error if one occurs.
func (c *FakeHadoops) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hadoopsResource, c.ns, name), &hadoopv1.Hadoop{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHadoops) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hadoopsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &hadoopv1.HadoopList{})
	return err
}

// Patch applies the patch and returns the patched hadoop.
func (c *FakeHadoops) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hadoopv1.Hadoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hadoopsResource, c.ns, name, pt, data, subresources...), &hadoopv1.Hadoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hadoopv1.Hadoop), err
}
